project 'PersonsExam.xcodeproj'

source 'https://github.com/CocoaPods/Specs'

platform :ios, '10.0'
use_frameworks!

# ignore all warnings from all pods, since Xcode is beta
inhibit_all_warnings!

  target 'PersonsExam' do
    
    pod 'EFInternetIndicator',  '0.4.0'           # Reachability
    pod 'Kingfisher',           '4.10.0'          # Image loading with built-in caching system.
    pod 'Moya',                 '11.0.2'          # Networking Abstraction Layer
    pod 'SnapKit',              '4.0.1'           # Constraint Programmatically.
    pod 'SwiftyJSON',           '4.1.0'           # Parsing of JSON Data
   
    pod 'RxSwift',              '4.3.1'           # Reactive/Functional Programming Framework
    pod 'RxCocoa',              '4.3.1'           # Reactive/Functional Programming Framework

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end

  end

  target 'PersonsExamUITests' do

  end
